version: '3'

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    volumes:
      - ./data/postgres/data:/var/lib/postgres/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    ports:
      - 18080:8080
    depends_on:
      postgres:
        condition: service_healthy 
